chore: add usdc
sygmaprotocol/sygma-shared-configuration pull request #182
Opened 2024-10-08 12:47 UTC by tcar121293

## Description
- add USDC to ethereum, base, b3, optimism, arbitrum
- add new erc20 handler to ethereum, base, b3, optimism, arbitrum
- add balance checker configuration for USDC on ethereum, base, b3, optimism, arbitrum

2024-10-08 13:56 UTC, MakMuftic requested changes

2024-10-08 13:56 UTC, MakMuftic commented on mainnet/shared-config-mainnet.json
> +          "resourceId": "0x0000000000000000000000000000000000000000000000000000000000000003",
I believe this is a mistake, you are overriding native with this

2024-10-09 09:42 UTC, nmlinaric approved these changes

2024-10-09 10:01 UTC, MakMuftic approved these changes

2024-10-09 10:45 UTC, merged