chore: mainnet cleanup
sygmaprotocol/sygma-shared-configuration pull request #198
Opened 2024-12-16 15:17 UTC by MakMuftic

## Updated networks

**cronos**
block time: 5.5s | block interval 25
deposit processing time <2min

**base**
block time: 2s | block interval 10
deposit processing time <0.5min

**gnosis**
block time: 5s | block interval 25
deposit processing time <2min

**polygon**
block time: 2s | block interval 25
deposit processing time <1min

**b3**
block time: 1s | block interval 10
deposit processing time <15s

**arbitrum**
block time: <1s | block interval 25
deposit processing time <15s

**optimism**
block time: 2s | block interval 25
deposit processing time <1min

2024-12-16 15:26 UTC, mpetrun5 approved these changes

2024-12-16 15:36 UTC, tcar121293 requested changes

2024-12-16 15:36 UTC, tcar121293 commented on mainnet/shared-config-mainnet.json
>        "feeHandlers": [
You didn't configure blockInterval for optimism
There is missmatch for blockInterval in your PR description and what you configured for gnosis and  cronos

2024-12-17 10:55 UTC, tcar121293 approved these changes

2024-12-17 11:36 UTC, merged